# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  reactjs-build-and-test:
    docker:
      - image: circleci/node:14.17-browsers
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-v1-{{ checksum "client/package-lock.json" }}
      - run:
          name: Install Dependencies
          command: cd client && npm ci
      - save_cache:
          key: npm-cache-v1-{{ checksum "client/package-lock.json" }}
          paths:
            - /home/circleci/.npm
      - run:
          name: Run ReactJS Tests
          command: cd client && npm test -- --json --outputFile=coverage.json
      - run:
          name: mv output to root for codecov
          command: mv client/coverage.json .
      - store_test_results:
          path: coverage.json
      - run:
          name: Send to CodeCov
          command: bash <(curl -s https://codecov.io/bash)


workflows:
  # Below is the definition of your workflow.
  # Inside the workflow, you provide the jobs you want to run, e.g this workflow runs the build-and-test job above.
  # CircleCI will run this workflow on every commit.
  # For more details on extending your workflow, see the configuration docs: https://circleci.com/docs/2.0/configuration-reference/#workflows
  sample:
    jobs:
      - reactjs-build-and-test

